# DigitalOcean App Platform Specification
# Horse Racing Prediction Application - Budget-Friendly Option

name: horse-racing-prediction
region: nyc

# Main application service
services:
- name: web
  source_dir: /
  github:
    repo: survivaltek2-ux/horse-racing-prediction
    branch: main
    deploy_on_push: true
  
  # Build configuration
  build_command: |
    pip install --upgrade pip
    pip install -r requirements.txt
  
  # Runtime configuration
  run_command: gunicorn --bind 0.0.0.0:8080 --workers 2 --timeout 120 app:app
  
  # Environment settings
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs  # $12/month - 512MB RAM, 1 vCPU
  
  # HTTP configuration
  http_port: 8080
  
  # Health check
  health_check:
    http_path: /api/providers
    initial_delay_seconds: 60
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  
  # Environment variables
  envs:
  - key: FLASK_ENV
    value: production
  - key: DEBUG
    value: "False"
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: SECRET_KEY
    value: ${SECRET_KEY}  # Set in App Platform dashboard
    type: SECRET
  - key: API_TIMEOUT
    value: "30"
  - key: API_MAX_RETRIES
    value: "3"
  - key: SESSION_COOKIE_SECURE
    value: "True"
  - key: SESSION_COOKIE_HTTPONLY
    value: "True"
  
  # Resource limits
  source_dir: /
  dockerfile_path: Dockerfile

# Database service
databases:
- name: db
  engine: PG
  version: "13"
  size: db-s-1vcpu-1gb  # $15/month - 1GB RAM, 1 vCPU, 10GB storage
  num_nodes: 1
  
# Static site for documentation (optional)
static_sites:
- name: docs
  source_dir: /docs
  github:
    repo: survivaltek2-ux/horse-racing-prediction
    branch: main
  build_command: echo "Static documentation site"
  output_dir: /docs
  index_document: index.html
  error_document: 404.html
  routes:
  - path: /docs

# Domain configuration (optional)
domains:
- domain: your-domain.com
  type: PRIMARY
  wildcard: false
  zone: your-domain.com

# Features
features: []

# Jobs (for background tasks)
jobs:
- name: model-training
  source_dir: /
  github:
    repo: survivaltek2-ux/horse-racing-prediction
    branch: main
  
  # Run model training job
  run_command: python train_ml_models.py
  
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-s  # $24/month for ML training
  
  # Schedule: Run daily at 2 AM UTC
  kind: PRE_DEPLOY  # or CRON for scheduled jobs
  
  envs:
  - key: FLASK_ENV
    value: production
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: SECRET_KEY
    value: ${SECRET_KEY}
    type: SECRET