# Prometheus Configuration for Production Environment
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'horse-racing-prediction'
    environment: 'production-dev'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # Application servers
  - job_name: 'flask-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL monitoring
  - job_name: 'postgres-master'
    static_configs:
      - targets: ['postgres-exporter-master:9187']
    scrape_interval: 15s

  - job_name: 'postgres-slave'
    static_configs:
      - targets: ['postgres-exporter-slave:9187']
    scrape_interval: 15s

  # Redis monitoring
  - job_name: 'redis-master'
    static_configs:
      - targets: ['redis-exporter-master:9121']
    scrape_interval: 15s

  - job_name: 'redis-slave'
    static_configs:
      - targets: ['redis-exporter-slave:9121']
    scrape_interval: 15s

  - job_name: 'redis-sentinel'
    static_configs:
      - targets: ['redis-exporter-sentinel:9121']
    scrape_interval: 15s

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Elasticsearch monitoring
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s

  # Logstash monitoring
  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash:9600']
    metrics_path: '/_node/stats'
    scrape_interval: 30s

  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://nginx/health
        - https://nginx/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom application metrics
  - job_name: 'app-custom-metrics'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    honor_labels: true

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true