#cloud-config
# Cloud-init configuration for faster SSH startup

# Update packages and install essential tools
package_update: true
package_upgrade: false

packages:
  - curl
  - wget
  - git
  - docker.io
  - docker-compose

# Ensure SSH service is enabled and started
runcmd:
  - systemctl enable ssh
  - systemctl start ssh
  - systemctl restart ssh
  - ufw allow ssh
  - echo "SSH service configured" > /var/log/cloud-init-ssh.log

# Configure SSH for faster startup
write_files:
  - path: /etc/ssh/sshd_config.d/99-custom.conf
    content: |
      UseDNS no
      GSSAPIAuthentication no
      PermitRootLogin yes
      PubkeyAuthentication yes
      PasswordAuthentication no
    permissions: '0644'

# Final commands to ensure everything is ready
final_message: "Cloud-init setup complete. SSH should be available."